name: Patch Bazzite Kernel Source

on:
  workflow_dispatch:
  pull_request:
    paths: &paths
      - .github/workflows/release.yaml
      - linux-kernel-bc250.patch
    types:
      - opened
      - synchronize
  push:
    branches:
      - main
      - renovate/**
    paths: *paths

jobs:
  patch-kernel:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout local repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: local
      - name: Checkout upstream repository
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          path: upstream
          ref: 6.17.7-ba25
          repository: bazzite-org/kernel-bazzite
      - name: Add BC-250 GPU Frequency Patch
        run: |
          cp ./local/patch-99-bc250-gpu-freq.patch ./upstream/
          PATCH_SOURCE_LINE=$(echo "$(grep -m1 -n "Patch999999: linux-kernel-test.patch" ./upstream/kernel.spec | cut -d: -f1) - 3" | bc)
          sed -i "${PATCH_SOURCE_LINE}i Patch99: patch-99-bc250-gpu-freq.patch" ./upstream/kernel.spec

          APPLY_PATCH_LINE=$(echo "$(grep -m1 -n "ApplyOptionalPatch linux-kernel-test.patch" ./upstream/kernel.spec | cut -d: -f1) - 2" | bc)
          sed -i "${APPLY_PATCH_LINE}i ApplyOptionalPatch patch-99-bc250-gpu-freq.patch" ./upstream/kernel.spec
      - name: Debug kernel.spec
        run: |
          sed -i "s/\*\) $patch_command/\*\) cat drivers\/gpu\/drm\/amd\/pm\/swsmu\/smu11\/cyan_skillfish_ppt.c \&\& $patch_command/" ./upstream/kernel.spec
          sed -i "s/patch_command='git --work-tree=. apply'/patch_command='git --work-tree=. apply --reject'/" ./upstream/kernel.spec
          cat ./upstream/kernel.spec
          ls -l ./upstream/patch*
      - name: Create Build Environment
        run: |
          sudo podman build upstream --tag 'fedora_builder' \
            --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
            --build-arg FEDORA_VERSION=${{ matrix.fedora_version }}
          sudo podman image prune -f
          TARFILE_RELEASE=$(sed -n 's/^%define[[:space:]]\+tarfile_release[[:space:]]\+//p' ./upstream/kernel.spec)
          echo "TARFILE_RELEASE is $TARFILE_RELEASE"
          echo "$TARFILE_RELEASE" > ./upstream/.tarfile-release
          linuxfname="./upstream/linux-${TARFILE_RELEASE}.tar.xz"
          if [ ! -f "${linuxfname}" ]; then
            echo "Downloading ${linuxfname}"
            curl -L -o "${linuxfname}" "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${TARFILE_RELEASE}.tar.xz"
          fi
      - name: Build Kernel RPMs
        run: |
          sudo podman run \
            --rm \
            -v ./upstream:/workspace \
            -e UID=$UID \
            -e GID=$GID \
            -e ARCH=x86_64 \
            -e FEDORA_VERSION=${{ matrix.fedora_version }} \
            fedora_builder rpmbuild \
              --with bazzite \
              --with ubsb \
              --define '_topdir %(pwd)/build' \
              --define '_builddir %{_topdir}/BUILD' \
              --define '_rpmdir %{_topdir}/RPMS' \
              --define '_srcrpmdir %{_topdir}/SRPMS' \
              --define '_sourcedir %(pwd)/' \
              --define '_specdir %(pwd)/' \
              -ba kernel.spec
      - name: Extract DRPM
        run: |
          mkdir -p ./upstrea/build/DRPMS
          mv ./upstream/RPMS/kernel-debuginfo-*.rpm ./upstream/build/DRPMS/
      - name: Upload DRPM
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: debuginfo-fc${{ matrix.fedora_version }}
          path: ./upstream/build/DRPMS/kernel-*.src.rpm
      - name: Upload RPM
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: rpm-fc${{ matrix.fedora_version }}
          path: ./upstream/build/RPMS/kernel-*.src.rpm
      - name: Upload SRPM
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f # v7.0.0
        with:
          name: srpm-fc${{ matrix.fedora_version }}
          path: ./upstream/build/SRPMS/kernel-*.src.rpm
      - name: Generate artifact attestation
        if: github.event_name != 'pull_request' && !contains('refs/heads/renovate', github.ref)
        uses: actions/attest@59d89421af93a897026c735860bf21b6eb4f7b26 # v4.1.0
        with:
          subject-path: |
            ./build/DRPMS/kernel-debuginfo-*.rpm
            ./build/RPMS/kernel-*.rpm
            ./build/SRPMS/kernel-*.rpm
    strategy:
      matrix:
        fedora_version:
          - 43
          - 44
      
  # TODO: rewrite to handle this correctly after a release is made!
  # TODO: setup release process
  upload-to-copr:
    container:
      image: fedora:latest
    environment: Production
    if: github.event_name != 'pull_request' && !contains('refs/heads/renovate', github.ref)
    needs: patch-kernel
    steps:
      - name: Download SRPM
        uses: actions/download-artifact@70fc10c6e5e1ce46ad2ea6f2b72d43f7d47b13c3 # v8.0.0
        with:
          merge-multiple: true
          path: SRPMS
          pattern: srpm-fc*
      - name: Install COPR CLI
        run: dnf install -y copr-cli
      - name: Authenticate with COPR
        run: |
          mkdir -p ~/.config
          cat > ~/.config/copr <<EOF
          [copr-cli]
          login = ${{ secrets.COPR_LOGIN }}
          username = sdwilsh
          token = ${{ secrets.COPR_TOKEN }}
          copr_url = https://copr.fedorainfracloud.org
          EOF
      - name: Upload to COPR
        run: |
          copr-cli build sdwilsh/kernel-bazzite-bc-250 SRPMS/kernel-*.src.rpm
    runs-on: ubuntu-latest
