name: Patch Bazzite Kernel Source

on:
  workflow_dispatch:
  # TODO:
  # - setup renovate to update this file on new bazzite kernel releases
  # - actually setup COPR
  pull_request_target:
    paths:
      - .github/workflows/release.yaml
      - linux-kernel-bc250.patch
    types:
      - opened
      - synchronize

jobs:
  patch-kernel:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fedora_version:
          - 43
    steps:
      - name: Checkout local repository
        uses: actions/checkout@v4
        with:
          path: local

      - name: Checkout upstream repository
        uses: actions/checkout@v4
        with:
          path: upstream
          ref: 6.17.7-ba25
          repository: bazzite-org/kernel-bazzite

      - name: Create Build Environment
        run: |
          FEDORA_VERSION="${{ matrix.fedora_version }}"
          sudo podman build upstream --tag 'fedora_builder' \
            --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
            --build-arg FEDORA_VERSION=${FEDORA_VERSION}
          sudo podman image prune -f
          TARFILE_RELEASE=$(sed -n 's/^%define[[:space:]]\+tarfile_release[[:space:]]\+//p' ./upstream/kernel.spec)
          echo "TARFILE_RELEASE is $TARFILE_RELEASE"
          echo "$TARFILE_RELEASE" > ./upstream/.tarfile-release
          linuxfname="./upstream/linux-${TARFILE_RELEASE}.tar.xz"
          if [ ! -f "${linuxfname}" ]; then
            echo "Downloading ${linuxfname}"
            curl -L -o "${linuxfname}" "https://cdn.kernel.org/pub/linux/kernel/v6.x/linux-${TARFILE_RELEASE}.tar.xz"
          fi
      
      - name: Add BC-250 Frequency Patch
        run:
          cp ./local/linux-kernel-bc250.patch ./upstream/patch-99-bc250-freq.patch
      # TODO: remove this step
      - name: Debug
        run: ls -la ./upstream
      - name: Build Kernel SRPMs
        run: |
          sudo podman run \
            --rm \
            -v ./upstream:/workspace \
            -e UID=$UID \
            -e GID=$GID \
            -e ARCH=x86_64 \
            -e FEDORA_VERSION=${{ matrix.fedora_version }} \
            fedora_builder rpmbuild \
              --with bazzite \
              --with ubsb \
              --define '_topdir %(pwd)/build' \
              --define '_builddir %{_topdir}/BUILD' \
              --define '_rpmdir %{_topdir}/RPMS' \
              --define '_srcrpmdir %{_topdir}/SRPMS' \
              --define '_sourcedir %(pwd)/' \
              --define '_specdir %(pwd)/' \
              -bs kernel.spec

      - name: Authenticate with COPR
        run: |
          mkdir -p ~/.config
          cat > ~/.config/copr <<EOF
          [copr-cli]
          login = ${{ secrets.COPR_LOGIN }}
          username = sdwilsh
          token = ${{ secrets.COPR_TOKEN }}
          copr_url = https://copr.fedorainfracloud.org
          EOF
        if: github.event_name != 'pull_request_target'

      # TODO: remove this step
      - name: Log Upload Targets
        run: ls -la ./upstream/build/SRPMS/kernel-*.src.rpm
        if: github.event_name == 'pull_request_target'
      - name: Upload to COPR
        run: |
          copr-cli build sdwilsh/kernel-bazzite-bc250 ./upstream/build/SRPMS/kernel-*.src.rpm
        if: github.event_name != 'pull_request_target'
